name: Build and push to Docker Hub

on:
  push:
    branches: [ "master" ]   # Ojo aquí, comprueba si tu repo usa 'main' o 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código del repo
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y subir imagen
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webapp-tomcat:latest
